@baseURL=http://localhost:8080/api
@email=john.doe@example.com
@password=password123

### Register a new user
POST {{baseURL}}/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "{{email}}",
  "password": "{{password}}"
}

### Login user
# @name login
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Get current user data
GET {{baseURL}}/auth/current
Authorization: Bearer {{login.response.body.data.token}}
Accept: application/json
